project14/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *
import specific

urlpatterns = [
    path('admin/', admin.site.urls),
    path('one/',one,name='one'),
    path('two/',two,name='two'),

    path('specific/',include('specific.urls')),
    
]

specific/urls.py
from specific.views import *
from django.urls import path

app_name='something'

urlpatterns=[
    path('three/',three,name='three'),
    path('four/',four,name='four'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def one(request):
    return render(request,'one.html')

def two(request):
    return render(request,'two.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def three(request):
    return render(request,'three.html')

def four(request):
    return render(request,'four.html')

templates/four.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hey its me</h1>
    <h2><a href="{% url 'one' %}">go to first page</a><br></h2>

    <h2><a href="{% url 'two' %}">go to second page</a><br></h2>

    

    <h2><a href="{% url 'something:three' %}">go to third page</a></h2>
</body>
</html>

templates/one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hey its abinash</h1>
<h2><a href="{% url 'two' %}">go to second page</a><br></h2>

<h2> <a href="{% url 'something:three' %}">go to third page</a><br></h2>

<h2><a href="{% url 'something:four' %}">go to fourth page</a></h2>
</body>
</html>

templates/three.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hey its u</h1>
<h2><a href="{% url 'one' %}">go to first page</a><br></h2>

<h2><a href="{% url 'two' %}">go to second page</a><br></h2>

    

<h2><a href="{% url 'something:four' %}">go to fourth page</a></h2>
</body>
</html>

templates/two.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hey its swayam</h1>
    <h2><a href="{% url 'one' %}">go to first page</a><br></h2>

    <h2><a href="{% url 'something:three' %}">go to third page</a><br></h2>

<h2><a href="{% url 'something:four' %}">go to fourth page</a></h2>
</body>
</html>